spring:
  application:
    name: gatewayserver
  jmx:
    enabled: false
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka
zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-milis: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 60000
  ReadTimeout: 60000
  
server:
  port: 8000